---
#settings for deployments

username: mellonaut
hostname: ash
ssh_login_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32343839363936393431303932306464666632386139323237353638643963623833313866336566
          3739393932623733333066373466626365363765346364640a633435626562363139653932626661
          30326533373630646638343530633939393936646366343662643434353965666637323337303266
          3537613865346265340a343038633833366433636363316231366364333333346361353239353537
          3531

my_ssh_pub_key: "/home/earth/.ssh/id_ed25519.pub"

timesync_timezone: America/New_York